### ISSUE TITLE
icon getter is not used in the code

### ISSUE THREAD

**Issue by sukima** [NullVoxPopuli/render-scan#1]
the `get icon()` getter is not used. Looks like title is prefixed with an `x` instead.

**Comment by NullVoxPopuli** [comment]
ah, it should just be removed then. thank you for reporting!

**Comment by NullVoxPopuli** [comment]
Removed and released in 0.0.3

**Comment by sukima** [comment]
> ah, it should just be removed then. thank you for reporting!

Oh? You didn't like the icons?

**Comment by NullVoxPopuli** [comment]
nah, they added a lot of visual noise
